name: test-apax
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout actions repository"
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: "Setup the apax runner"
        uses: simatic-ax/actions/setup-apax-runner@main
        with:
          APAX_TOKEN: ${{ secrets.APAX_TOKEN }}