name: test-apax
on:
  workflow_call:
    secrets:
      APAX_TOKEN:
        description: "Access token for installing apax sdk"
        required: true
      SIMATIC_AX_TOKEN:
        description: "Access token for installing packages from github registry, required if LOGIN_SIMATIC_AX is true"
        required: false
    inputs:
      LOGIN_SIMATIC_AX:
        type: boolean
        default: false
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout actions repository"
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: "Setup the apax runner"
        uses: simatic-ax/actions/setup-apax-runner@stable
        with:
          APAX_TOKEN: ${{ secrets.APAX_TOKEN }}